/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = function (knex) {
  return knex('words')
    .del() // Delete existing data
    .then(() => {
      return knex('words').insert([
        {
          hawaiianWord: "'Ula, 'ula'ula",
          englishTranslation: "Red (a sacred color associated with royalty)",
          type: "adjective",
          pronunciation: "oo-LAH-oo-lah",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "'Alani",
          englishTranslation: "Orange",
          type: "adjective",
          pronunciation: "ah-LAH-nee",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Melemele",
          englishTranslation: "Yellow",
          type: "adjective",
          pronunciation: "meh-leh-MEH-leh",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "ʻŌmaʻomaʻo",
          englishTranslation: "Green",
          type: "adjective",
          pronunciation: "oh-MAH-oh-MAH-oh",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Uliuli",
          englishTranslation: "Blue",
          type: "adjective",
          pronunciation: "oo-LEE-oo-LEE",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Poni",
          englishTranslation: "Purple",
          type: "adjective",
          pronunciation: "poh-NEE",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Ākala",
          englishTranslation: "Pink",
          type: "adjective",
          pronunciation: "ah-KAH-lah",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Waioleka",
          englishTranslation: "Violet",
          type: "adjective",
          pronunciation: "vie-oh-LEH-kah",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "'Ele'ele'",
          englishTranslation: "Black",
          type: "adjective",
          pronunciation: "eh-LEH-eh-LEH",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Ke'oke'o",
          englishTranslation: "White",
          type: "adjective",
          pronunciation: "keh-OH-keh-OH",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "'Ekahi",
          englishTranslation: "One",
          type: "noun/adjective",
          pronunciation: "EH-kah-hee",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Elua",
          englishTranslation: "Two",
          type: "noun/adjective",
          pronunciation: "eh-LOO-ah",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "'Ekolu",
          englishTranslation: "Three",
          type: "noun/adjective",
          pronunciation: "EH-koh-loo",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "'Ehā",
          englishTranslation: "Four",
          type: "noun/adjective",
          pronunciation: "eh-HAH",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Elima",
          englishTranslation: "Five",
          type: "noun/adjective",
          pronunciation: "eh-LEE-mah",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Eono",
          englishTranslation: "Six",
          type: "noun/adjective",
          pronunciation: "eh-OH-noh",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Ehiku",
          englishTranslation: "Seven",
          type: "noun/adjective",
          pronunciation: "eh-HEE-koo",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Ewalu",
          englishTranslation: "Eight",
          type: "noun/adjective",
          pronunciation: "eh-WAH-loo",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "'Eiwa",
          englishTranslation: "Nine",
          type: "noun/adjective",
          pronunciation: "aye-Vah",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "'Umi",
          englishTranslation: "Ten",
          type: "noun/adjective",
          pronunciation: "oo-MEE",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Kaumaha",
          englishTranslation: "Sad",
          type: "noun/adjective",
          pronunciation: "kow-MAH-hah",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Pololi",
          englishTranslation: "Hungry",
          type: "noun/adjective",
          pronunciation: "poh-LOH-lee",
          soundsLike: null,
          example: null,
      },
      {
          hawaiianWord: "Luhi",
          englishTranslation: "Tired",
          type: "noun/adjective",
          pronunciation: "loo-HEE",
          soundsLike: null,
          example: null,
      },
      {
        hawaiianWord: "lumi kuke",
        englishTranslation: "kitchen",
        type: "noun/nominal adjective",
        pronunciation: "loo-me koo-keh",
        soundsLike: null,
        example: null,
      },
      {
        hawaiianWord: "'oma",
        englishTranslation: "oven",
        type: "noun",
        pronunciation: "oh-mah",
        soundsLike: null,
        example: null,
      },
      {
        hawaiianWord: "'oma",
        englishTranslation: "oven",
        type: "noun",
        pronunciation: "oh-mah",
        soundsLike: null,
        example: null,
      },
      {
        hawaiianWord: "'oma",
        englishTranslation: "oven",
        type: "noun",
        pronunciation: "oh-mah",
        soundsLike: null,
        example: null,
      },
      {
        hawaiianWord: "'oma",
        englishTranslation: "oven",
        type: "noun",
        pronunciation: "oh-mah",
        soundsLike: null,
        example: null,
      },
      {
        hawaiianWord: "kapuahi",
        englishTranslation: "stove",
        type: "noun",
        pronunciation: "kah-poo-wah-hee",
        soundsLike: null,
        example: null,
      },
      {
        hawaiianWord: "pahu hau",
        englishTranslation: "ice box",
        type: "noun",
        pronunciation: "pah-hoo how",
        soundsLike: null,
        example: null,
      },

      ]);
    });
};
